// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

#include "StudioProtocol.h"

namespace vsr::scivis_studio::protocol {

const char *toString(StudioMessageType type)
{
  switch (type) {
  case StudioMessageType::Hello:
    return "Hello";
  case StudioMessageType::Error:
    return "Error";
  case StudioMessageType::Ping:
    return "Ping";
  case StudioMessageType::Pong:
    return "Pong";
  case StudioMessageType::Disconnect:
    return "Disconnect";
  case StudioMessageType::Shutdown:
    return "Shutdown";
  case StudioMessageType::BootstrapBegin:
    return "BootstrapBegin";
  case StudioMessageType::BootstrapEnd:
    return "BootstrapEnd";
  case StudioMessageType::NewProject:
    return "NewProject";
  case StudioMessageType::OpenProject:
    return "OpenProject";
  case StudioMessageType::SaveProject:
    return "SaveProject";
  case StudioMessageType::ImportStaticDataset:
    return "ImportStaticDataset";
  case StudioMessageType::ImportFileAnimationDataset:
    return "ImportFileAnimationDataset";
  case StudioMessageType::DeclareFileAnimationDataset:
    return "DeclareFileAnimationDataset";
  case StudioMessageType::ReimportDataset:
    return "ReimportDataset";
  case StudioMessageType::RenameDataset:
    return "RenameDataset";
  case StudioMessageType::RemoveDataset:
    return "RemoveDataset";
  case StudioMessageType::LoadDataset:
    return "LoadDataset";
  case StudioMessageType::UnloadDataset:
    return "UnloadDataset";
  case StudioMessageType::RefreshDatasetAvailability:
    return "RefreshDatasetAvailability";
  case StudioMessageType::SaveDatasetArchive:
    return "SaveDatasetArchive";
  case StudioMessageType::LoadDatasetArchive:
    return "LoadDatasetArchive";
  case StudioMessageType::DiscoverDatasetCandidates:
    return "DiscoverDatasetCandidates";
  case StudioMessageType::IncorporateDatasetCandidate:
    return "IncorporateDatasetCandidate";
  case StudioMessageType::CreateShot:
    return "CreateShot";
  case StudioMessageType::RemoveShot:
    return "RemoveShot";
  case StudioMessageType::UpdateShot:
    return "UpdateShot";
  case StudioMessageType::SetActiveShot:
    return "SetActiveShot";
  case StudioMessageType::CreateLightRig:
    return "CreateLightRig";
  case StudioMessageType::CloneLightRig:
    return "CloneLightRig";
  case StudioMessageType::RemoveLightRig:
    return "RemoveLightRig";
  case StudioMessageType::RenameLightRig:
    return "RenameLightRig";
  case StudioMessageType::AddLightToRig:
    return "AddLightToRig";
  case StudioMessageType::RemoveLightFromRig:
    return "RemoveLightFromRig";
  case StudioMessageType::CreateCameraRig:
    return "CreateCameraRig";
  case StudioMessageType::RemoveCameraRig:
    return "RemoveCameraRig";
  case StudioMessageType::RenameCameraRig:
    return "RenameCameraRig";
  case StudioMessageType::SaveCameraRigArchive:
    return "SaveCameraRigArchive";
  case StudioMessageType::LoadCameraRigArchive:
    return "LoadCameraRigArchive";
  case StudioMessageType::SaveLightRigArchive:
    return "SaveLightRigArchive";
  case StudioMessageType::LoadLightRigArchive:
    return "LoadLightRigArchive";
  case StudioMessageType::CreateColorMap:
    return "CreateColorMap";
  case StudioMessageType::RenameColorMap:
    return "RenameColorMap";
  case StudioMessageType::RemoveColorMap:
    return "RemoveColorMap";
  case StudioMessageType::ListRoots:
    return "ListRoots";
  case StudioMessageType::ListDirectory:
    return "ListDirectory";
  case StudioMessageType::SetPlaying:
    return "SetPlaying";
  case StudioMessageType::RequestArrayHistogram:
    return "RequestArrayHistogram";
  case StudioMessageType::RenderShot:
    return "RenderShot";
  case StudioMessageType::CancelTask:
    return "CancelTask";
  case StudioMessageType::Pick:
    return "Pick";
  case StudioMessageType::ProjectOpReply:
    return "ProjectOpReply";
  case StudioMessageType::ProjectSnapshot:
    return "ProjectSnapshot";
  case StudioMessageType::TaskProgress:
    return "TaskProgress";
  case StudioMessageType::TaskCompleted:
    return "TaskCompleted";
  case StudioMessageType::TaskFailed:
    return "TaskFailed";
  case StudioMessageType::TimeAdvanceWarning:
    return "TimeAdvanceWarning";
  case StudioMessageType::PickReply:
    return "PickReply";
  case StudioMessageType::UIState:
    return "UIState";
  case StudioMessageType::TransferScene:
    return "TransferScene";
  case StudioMessageType::TransferLayer:
    return "TransferLayer";
  case StudioMessageType::ObjectAdded:
    return "ObjectAdded";
  case StudioMessageType::ObjectRemoved:
    return "ObjectRemoved";
  case StudioMessageType::SetObjectParameter:
    return "SetObjectParameter";
  case StudioMessageType::RemoveObjectParameter:
    return "RemoveObjectParameter";
  case StudioMessageType::SetNodeTransform:
    return "SetNodeTransform";
  case StudioMessageType::SetTime:
    return "SetTime";
  case StudioMessageType::SetOutline:
    return "SetOutline";
  case StudioMessageType::ViewportSettings:
    return "ViewportSettings";
  case StudioMessageType::SetFrameConfig:
    return "SetFrameConfig";
  case StudioMessageType::FrameConfig:
    return "FrameConfig";
  case StudioMessageType::SetEncodings:
    return "SetEncodings";
  case StudioMessageType::StartRendering:
    return "StartRendering";
  case StudioMessageType::StopRendering:
    return "StopRendering";
  case StudioMessageType::Frame:
    return "Frame";
  default:
    return "Unknown";
  }
}

} // namespace vsr::scivis_studio::protocol
